references:
  base: &base
    working_directory: ~/marp-web
    steps:
      - checkout

      - restore_cache:
          keys:
            - dependencies-{{ .Environment.CI_CACHE_KEY }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "yarn.lock" }}-{{ .Branch }}
            - dependencies-{{ .Environment.CI_CACHE_KEY }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "yarn.lock" }}-
            - dependencies-{{ .Environment.CI_CACHE_KEY }}-{{ .Environment.CIRCLE_JOB }}-

      - run: yarn install

      - save_cache:
          key: dependencies-{{ .Environment.CI_CACHE_KEY }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "yarn.lock" }}-{{ .Branch }}
          paths:
            - node_modules
            - ~/.cache/yarn

      - run:
          name: Prettier formatting
          command: yarn format:check

      - run:
          name: TypeScript type checking
          command: yarn check-ts

      - run:
          name: stylelint
          command: yarn lint:css

      - run:
          name: TSLint
          command: yarn lint:ts

      - run:
          name: Jest
          command: yarn test:coverage --ci --maxWorkers=2 --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT: tmp/test-results/jest.xml

      - run: yarn codecov

      - store_test_results:
          path: tmp/test-results

      - store_artifacts:
          path: ./coverage
          destination: coverage

version: 2
jobs:
  '10.15.3':
    <<: *base
    docker:
      - image: circleci/node:10.15.3

workflows:
  version: 2
  build:
    jobs:
      - 10.15.3
